# Generated by Django 4.2.16 on 2025-03-27 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transformations3d.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la transformación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('transformation_type', models.CharField(choices=[('HELMERT', 'Helmert'), ('MOLODENSKY_BADEKAS', 'Molodensky-Badekas')], default='HELMERT', max_length=20, verbose_name='Tipo de transformación')),
                ('parameters', models.JSONField(blank=True, verbose_name='Parámetros de transformación')),
                ('results', models.JSONField(blank=True, verbose_name='Resultados de la transformación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations3d', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransformationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_points', models.JSONField(validators=[transformations3d.validators.validate_points], verbose_name='Puntos de Origen')),
                ('destination_points', models.JSONField(validators=[transformations3d.validators.validate_points], verbose_name='Puntos de Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('transformation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_points', to='transformations3d.transformation3d', verbose_name='Puntos de transformación')),
            ],
        ),
    ]
