# Generated by Django 4.2.16 on 2024-11-22 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial del Equipo')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name='Marca del Equipo')),
                ('model', models.CharField(max_length=100, null=True, verbose_name='Modelo del Equipo')),
                ('equipment_type', models.CharField(choices=[('total_station', 'Estación Total'), ('gps', 'GPS'), ('level', 'Nivel'), ('theodolite', 'Teodolito'), ('other', 'Otro')], max_length=50, null=True, verbose_name='Tipo de Equipo')),
                ('distance_constant', models.FloatField(default=0.0, verbose_name='Constante de Distancia (m)')),
                ('distance_ppm', models.FloatField(default=0.0, verbose_name='PPM de Distancia')),
                ('angle', models.FloatField(default=0.0, verbose_name='Ángulo (segundos)')),
                ('direction', models.FloatField(default=0.0, verbose_name='Dirección (segundos)')),
                ('azimuth_bearing', models.FloatField(default=0.0, verbose_name='Azimut / Rumbo (segundos)')),
                ('zenith', models.FloatField(default=0.0, verbose_name='Cenit (segundos)')),
                ('elev_diff_constant', models.FloatField(default=0.0, verbose_name='Constante de Diferencia de Elevación (m)')),
                ('elev_diff_ppm', models.FloatField(default=0.0, verbose_name='PPM de Diferencia de Elevación')),
                ('horiz_instrument_error', models.FloatField(default=0.0, verbose_name='Error Horizontal del Instrumento (m)')),
                ('horiz_target_error', models.FloatField(default=0.0, verbose_name='Error Horizontal del Objetivo (m)')),
                ('vertical_error', models.FloatField(default=0.0, verbose_name='Error Vertical (m)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
