# Generated by Django 4.2.16 on 2024-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('TOTAL_STATION', 'Estación Total'), ('GPS', 'GPS'), ('LEVEL', 'Nivel'), ('THEODOLITE', 'Teodolito'), ('OTHER', 'Otro')], default='OTHER', max_length=50, null=True, verbose_name='Tipo de Equipo'),
        ),
    ]
